export const bookData = [
  {
    id: 1,
    img: "https://via.placeholder.com/150/FFFF00/000000?Text=google.com",
    title: "the brothers karamazov",
    author: "fyodor dostoevsky",
    rating: "5",
    genre: ["thriller"],
    quote: [
      "The more I love humanity in general, the less I love man in particular",
      `Above all, don't lie to yourself. The man who lies to himself and listens to his own lie comes to a point that he cannot distinguish the truth within him, or around him, and so loses all respect for himself and for others. And having no respect he ceases to love.`,
      `Love in action is a harsh and dreadful thing compared to love in dreams.`,
    ],
    review: {
      intro: `Fyodor Dostoevsky's "The Brothers Karamazov" stands as a timeless masterpiece, a literary journey that delves deep into the complexities of the human soul. Published in 1880, this Russian classic continues to captivate readers with its intricate plot, rich characterizations, and profound exploration of moral and existential dilemmas.`,
      summary: `Set in 19th-century Russia, "The Brothers Karamazov" revolves around the lives of the three Karamazov brothers: Dmitri, Ivan, and Alexei. The narrative unfolds against the backdrop of their tumultuous relationships with their father, Fyodor Pavlovich Karamazov, a libertine and unscrupulous man. The novel intricately weaves together themes of patricide, faith, morality, and the eternal struggle between good and evil.`,
      characterization: `Dostoevsky's characters are as vivid and multi-faceted as the intricate plot itself. Each brother represents a different facet of the human condition. Dmitri embodies passion and impulsivity, Ivan is the intellectual skeptic, and Alexei grapples with spiritual and moral dilemmas. The supporting cast adds depth and nuance to the story, creating a tapestry of personalities that reflect the complexity of human nature.`,
      themes: `At its core, "The Brothers Karamazov" is a philosophical exploration that raises profound questions about the existence of God, the nature of morality, and the consequences of human actions. Dostoevsky challenges readers to confront their own beliefs and moral convictions, pushing the boundaries of conventional thought.`,
      conclusion: `In conclusion, Fyodor Dostoevsky's "The Brothers Karamazov" is a profound and thought-provoking masterpiece that transcends time and cultural boundaries. Its exploration of the human condition, coupled with compelling characters and philosophical depth, makes it a must-read for anyone seeking a literary journey into the depths of the soul. This classic remains a testament to the enduring power of literature to illuminate the complexities of the human experience.`,
    },
  },
  {
    id: 2,
    img: "https://via.placeholder.com/150/FF0000/FFFFFF?Text=yttags.com",
    title: "pride and prejudice",
    author: "jane austen",
    rating: "3.5",
    genre: ["romance"],
    quote: [
      "I could easily forgive his pride, if he had not mortified mine.",
      `Vanity and pride are different things, though the words are often used synonymously. A person may be proud without being vain. Pride relates more to our opinion of ourselves, vanity to what we would have others think of us.`,
      `There is a stubbornness about me that never can bear to be frightened at the will of others. My courage always rises at every attempt to intimidate me.`,
    ],
    review: {
      intro: `Jane Austen's "Pride and Prejudice," first published in 1813, remains one of the most beloved novels in English literature. This enduring classic, with its sharp wit, keen social commentary, and timeless romance, continues to captivate readers more than two centuries after its publication.`,
      summary: `Set in the early 19th century, "Pride and Prejudice" tells the story of Elizabeth Bennet, a quick-witted and independent young woman, and her complex relationship with the wealthy and aloof Mr. Fitzwilliam Darcy. The narrative unfolds in the rural English countryside, where the five Bennet sisters navigate societal expectations, romantic entanglements, and the pursuit of suitable marriages. The novel explores themes of love, class, and the transformative power of self-awareness.`,
      characterization: `Austen's characters are richly drawn and enduringly memorable. Elizabeth Bennet stands out as a heroine ahead of her time, known for her intelligence, wit, and strong sense of self. Mr. Darcy, initially perceived as proud and distant, gradually reveals his true character and depth. The supporting cast, including the meddlesome Mrs. Bennet, the obsequious Mr. Collins, and the charming yet unscrupulous Mr. Wickham, adds layers of humor and intrigue to the story.`,
      themes: `"Pride and Prejudice" delves into the intricacies of social class and marriage, exposing the often superficial nature of societal judgments. Austen masterfully critiques the rigid class distinctions of her time, while also exploring themes of pride, prejudice, and the importance of personal growth and understanding in romantic relationships.`,
      conclusion: `"Pride and Prejudice" has left an indelible mark on literature and popular culture. Its themes and characters have inspired countless adaptations, retellings, and modern interpretations. Austen's sharp social critique and timeless exploration of human relationships ensure that the novel remains relevant and cherished by readers of all ages.`,
    },
  },
  {
    id: 3,
    img: "https://via.placeholder.com/150/000000/FFFFFF/?text=y2meta.com",
    title: "harry potter and the chamber of secrets",
    author: "j k rowling",
    rating: "4",
    genre: ["fiction", "thriller"],
    quote: [
      "When in doubt, go to the library.",
      `It is our choices, Harry, that show what we truly are, far more than our abilities.`,
      `Fame is a fickle friend, Harry. Celebrity is as celebrity does. Remember that.`,
    ],
    review: {
      intro: `Harry Potter and the Chamber of Secrets, the second installment in J.K. Rowling's globally celebrated series, takes readers deeper into the magical world of Hogwarts. Published in 1998, this novel continues the adventures of Harry Potter as he faces new challenges and uncovers more secrets about his past and the magical realm he inhabits.`,
      summary: `Returning for his second year at Hogwarts School of Witchcraft and Wizardry, Harry Potter faces an eerie warning from a house-elf named Dobby, who urges him not to return to school. Defying the warning, Harry reunites with his friends Hermione Granger and Ron Weasley, only to encounter a series of mysterious events. Students and staff are being petrified, and cryptic messages on the walls speak of the reopening of the Chamber of Secrets. As Harry delves into the school's dark history, he must confront the terrifying truth about the chamber and the sinister force behind its secrets.`,
      characterization: `Rowling's characters continue to develop in this second book, revealing deeper layers and complexities. Harry remains a brave and loyal protagonist, determined to protect his friends and uncover the truth. Hermione's intelligence and resourcefulness are invaluable, while Ron's loyalty and humor provide much-needed support. The introduction of new characters like the vain Professor Gilderoy Lockhart and the enigmatic Tom Riddle adds intrigue and depth to the narrative.`,
      themes: `"Harry Potter and the Chamber of Secrets" explores themes of identity, prejudice, and the power of choices. The novel delves into the dangers of bigotry, as seen through the fear of "Muggle-born" witches and wizards, and highlights the importance of courage and friendship in overcoming adversity. Rowling also emphasizes the significance of understanding one's past to shape a better future.`,
      conclusion: `"Harry Potter and the Chamber of Secrets" solidified the series' place in literary history, building on the success of the first book and expanding the wizarding world. The novel's blend of mystery and fantasy has made it a favorite among readers of all ages, contributing to the enduring popularity of the Harry Potter series. The themes of bravery and the fight against prejudice resonate deeply, making the book both entertaining and thought-provoking.`,
    },
  },
  {
    id: 4,
    img: "https://www.picsum.photos/",
    title: "to kill a mockingbird",
    author: "harper lee",
    rating: "4.5",
    genre: ["thriller"],
    quote: [
      "You never really understand a person until you consider things from his point of view... Until you climb inside of his skin and walk around in it.",
      `The one thing that doesn't abide by majority rule is a person's conscience.`,
      `People generally see what they look for and hear what they listen for.`,
    ],
    review: {
      intro: `Harper Lee's "To Kill a Mockingbird," published in 1960, is a cornerstone of American literature. This Pulitzer Prize-winning novel offers a poignant exploration of racial injustice, moral growth, and the complexities of human nature through the innocent eyes of a child. Set in the Deep South during the 1930s, it remains as relevant and impactful today as it was over six decades ago.`,
      summary: `The story is narrated by Scout Finch, a young girl growing up in the small town of Maycomb, Alabama. Alongside her brother, Jem, and their friend Dill, Scout experiences the joys and challenges of childhood. Their father, Atticus Finch, is a principled lawyer tasked with defending Tom Robinson, a black man falsely accused of raping a white woman, Mayella Ewell. As the trial unfolds, Scout and Jem witness the deep-seated racism and prejudice that permeate their community, leading to profound lessons about empathy, justice, and moral integrity.`,
      characterization: `Harper Lee's characters are richly drawn and memorable. Scout, with her curiosity and unfiltered perspective, provides a lens through which readers experience the story's events. Atticus Finch stands as a moral beacon, embodying the virtues of courage, empathy, and integrity. Jem's coming-of-age journey reflects the painful loss of innocence in the face of injustice. The supporting cast, including the reclusive Boo Radley and the bigoted Bob Ewell, adds depth and complexity to the narrative.`,
      themes: `"To Kill a Mockingbird" tackles profound themes such as racial injustice, moral courage, and the loss of innocence. The novel critiques the systemic racism and social inequalities of the time, urging readers to confront these issues with empathy and understanding. It also highlights the importance of standing up for what is right, even when faced with overwhelming opposition. Lee's exploration of these themes continues to resonate, encouraging readers to reflect on their own beliefs and actions.`,
      conclusion: `In conclusion, "To Kill a Mockingbird" by Harper Lee is a profound and timeless novel that continues to captivate and challenge readers. Its exploration of justice, empathy, and moral integrity remains relevant, encouraging readers to reflect on their own values and actions. Through its memorable characters, compelling narrative, and powerful themes, the novel stands as a testament to the enduring power of literature to inspire change and understanding.`,
    },
  },
  {
    id: 5,
    img: "https://via.placeholder.com/150/000000/FFFFFF/?text=y2meta.com",
    title: "crime and punishment",
    author: "fyodor dostoevsky",
    rating: "5",
    genre: ["thriller"],
    quote: [
      "I could easily forgive his pride, if he had not mortified mine.",
      `Vanity and pride are different things, though the words are often used synonymously. A person may be proud without being vain. Pride relates more to our opinion of ourselves, vanity to what we would have others think of us.`,
      `There is a stubbornness about me that never can bear to be frightened at the will of others. My courage always rises at every attempt to intimidate me.`,
    ],
    review: {
      intro: `Fyodor Dostoevsky's "Crime and Punishment," first published in 1866, is a seminal work in world literature, renowned for its deep psychological insight and philosophical depth. This Russian classic delves into the mind of its tormented protagonist, exploring themes of guilt, redemption, and the moral implications of crime.`,
      summary: `The novel centers on Rodion Raskolnikov, a destitute former student living in St. Petersburg. Desperate and disillusioned, he formulates a plan to murder a greedy pawnbroker, rationalizing that the act will free him from poverty and benefit society by eliminating a worthless person. However, after committing the crime, Raskolnikov is consumed by paranoia, guilt, and a deepening existential crisis. As the psychological and moral consequences of his actions unfold, he encounters various characters who influence his journey towards eventual confession and redemption.`,
      characterization: `Dostoevsky’s characters are complex and multifaceted. Raskolnikov is a deeply conflicted antihero, whose intellectual arrogance and internal torment drive the novel’s narrative. Supporting characters such as the compassionate Sonia Marmeladov, the morally ambiguous Svidrigailov, and the persistent investigator Porfiry Petrovich add richness to the story, each representing different aspects of human nature and morality.`,
      themes: `"Crime and Punishment" grapples with profound themes, including the nature of justice, the psychology of crime, and the possibility of redemption. The novel examines the conflict between utilitarian justifications for immoral actions and the innate moral laws that govern human conscience. Through Raskolnikov’s journey, Dostoevsky explores the devastating effects of isolation, pride, and guilt, ultimately suggesting that true redemption is found through suffering and moral awakening.`,
      conclusion: `"Crime and Punishment" has had a profound impact on literature and philosophy, influencing countless writers and thinkers. Its exploration of the human psyche and moral dilemmas continues to resonate with readers, making it a timeless work that remains relevant in contemporary discussions of ethics and justice. The novel’s enduring appeal lies in its ability to engage readers with its psychological depth and its exploration of universal themes.
      
      In conclusion, Fyodor Dostoevsky's "Crime and Punishment" is a psychological and philosophical masterpiece that delves into the darkest corners of the human mind. Its exploration of guilt, redemption, and the moral complexities of crime makes it a compelling and intellectually stimulating read. Through its richly drawn characters and profound themes, the novel continues to captivate and challenge readers, solidifying its place as one of the greatest works of world literature.`,
    },
  },
  {
    id: 6,
    img: "https://via.placeholder.com/150/000000/FFFFFF/?text=y2meta.com",
    title: "war and peace",
    author: "leo tolstoy",
    rating: "5",
    genre: [
      "novel",
      "history",
      "historical fiction",
      "war",
      "romance",
      "philosophy",
    ],
    quote: [
      "We can know only that we know nothing. And that is the highest degree of human wisdom.",
      `The whole world is divided for me into two parts: one is she, and there is all happiness, hope, light; the other is where she is not, and there is dejection and darkness...`,
      `The strongest of all warriors are these two — Time and Patience.`,
    ],
    review: {
      intro: `Leo Tolstoy's "War and Peace," first published in 1869, stands as one of the greatest literary achievements in history. This monumental work offers a sweeping narrative of Russian society during the Napoleonic Wars, weaving together historical events, philosophical reflections, and the intimate lives of its characters. Tolstoy’s epic explores the complexities of human experience, blending the grandeur of history with the depth of individual consciousness.`,
      summary: `"War and Peace" spans the years 1805 to 1815, chronicling the impact of the Napoleonic Wars on Russian aristocracy. The novel follows the intertwined lives of several prominent families, primarily the Rostovs, the Bolkonskys, and the Bezukhovs. Central characters include the earnest and idealistic Pierre Bezukhov, the introspective Prince Andrei Bolkonsky, and the spirited Natasha Rostov. As they navigate love, loss, and the turbulence of war, their personal journeys reflect broader societal changes and existential questions. The novel juxtaposes intimate domestic scenes with grand historical events, creating a rich tapestry of human experience.`,
      characterization: `Tolstoy’s characters are vivid and multifaceted, embodying a range of human emotions and experiences. Pierre Bezukhov’s quest for meaning and moral purpose, Prince Andrei’s search for glory and eventual disillusionment, and Natasha Rostov’s passionate and impetuous nature are deeply compelling. The novel’s expansive cast includes numerous memorable figures, each contributing to the intricate narrative and thematic richness. Tolstoy’s keen psychological insight and empathy allow readers to connect deeply with his characters, despite the historical and cultural distance.`,
      themes: `"War and Peace" explores themes of fate and free will, the nature of history, and the search for meaning in a chaotic world. Tolstoy examines the interplay between individual agency and historical forces, questioning the deterministic views of history and emphasizing the moral responsibility of individuals. The novel also delves into the contrasts between war and peace, public duty and private life, and the spiritual and material aspects of existence. Tolstoy’s philosophical reflections challenge readers to consider profound questions about life, love, and the human condition.`,
      conclusion: `"War and Peace" has left an indelible mark on world literature, influencing countless writers and thinkers. Its epic scale and profound exploration of human experience continue to captivate readers, making it a cornerstone of literary education and scholarship. The novel’s enduring relevance lies in its ability to speak to universal human concerns, transcending its historical context to offer timeless insights into the nature of life and history.
      
      In conclusion, Leo Tolstoy's "War and Peace" is a monumental work of literature that masterfully blends historical narrative, philosophical inquiry, and deep psychological insight. Its exploration of the human condition amidst the backdrop of historical upheaval remains as compelling and relevant today as it was over a century ago. Through its richly drawn characters and profound themes, "War and Peace" continues to offer readers an unparalleled literary experience, solidifying its place as one of the greatest novels ever written.`,
    },
  },
];
